format = """
[  ](bg:#769ff0 fg:#161616)\
$directory\
[](fg:#769ff0 bg:#464646)\
$git_branch\
$git_status\
[](fg:#464646 bg:#202020)\
$nodejs\
$rust\
$golang\
$python\
[](fg:#202020 bg:#0f0f0f)\
$time\
[ ](fg:#0f0f0f)\
\n$character"""

[directory]
style = "bold fg:#161616 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#464646"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#464646)]($style)'

[git_status]
style = "bg:#394260"
ahead = '⇡${count}'
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#464646)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#202020)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#202020)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#202020)]($style)'

[python]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#202020)]($style)'


[time]
disabled = true 
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'